var elementorFrontendConfig = {
    environmentMode: { edit: !1, wpPreview: !1, isScriptDebug: !1 },
    i18n: {
      shareOnFacebook: "Share on Facebook",
      shareOnTwitter: "Share on Twitter",
      pinIt: "Pin it",
      download: "Download",
      downloadImage: "Download image",
      fullscreen: "Fullscreen",
      zoom: "Zoom",
      share: "Share",
      playVideo: "Play Video",
      previous: "Previous",
      next: "Next",
      close: "Close",
      a11yCarouselWrapperAriaLabel:
        "Carousel | Horizontal scrolling: Arrow Left & Right",
      a11yCarouselPrevSlideMessage: "Previous slide",
      a11yCarouselNextSlideMessage: "Next slide",
      a11yCarouselFirstSlideMessage: "This is the first slide",
      a11yCarouselLastSlideMessage: "This is the last slide",
      a11yCarouselPaginationBulletMessage: "Go to slide",
    },
    is_rtl: !1,
    breakpoints: { xs: 0, sm: 480, md: 768, lg: 1025, xl: 1440, xxl: 1600 },
    responsive: {
      breakpoints: {
        mobile: {
          label: "Mobile Portrait",
          value: 767,
          default_value: 767,
          direction: "max",
          is_enabled: !0,
        },
        mobile_extra: {
          label: "Mobile Landscape",
          value: 880,
          default_value: 880,
          direction: "max",
          is_enabled: !1,
        },
        tablet: {
          label: "Tablet Portrait",
          value: 1024,
          default_value: 1024,
          direction: "max",
          is_enabled: !0,
        },
        tablet_extra: {
          label: "Tablet Landscape",
          value: 1200,
          default_value: 1200,
          direction: "max",
          is_enabled: !0,
        },
        laptop: {
          label: "Laptop",
          value: 1366,
          default_value: 1366,
          direction: "max",
          is_enabled: !0,
        },
        widescreen: {
          label: "Widescreen",
          value: 2400,
          default_value: 2400,
          direction: "min",
          is_enabled: !1,
        },
      },
    },
    version: "3.24.3",
    is_static: !1,
    experimentalFeatures: {
      additional_custom_breakpoints: !0,
      container: !0,
      container_grid: !0,
      e_swiper_latest: !0,
      e_nested_atomic_repeaters: !0,
      e_onboarding: !0,
      home_screen: !0,
      "ai-layout": !0,
      "landing-pages": !0,
      "nested-elements": !0,
      "link-in-bio": !0,
      "floating-buttons": !0,
    },
    urls: {
      assets:
        "https:\/\/wp.webtend.net\/noxfolio\/wp-content\/plugins\/elementor\/assets\/",
      ajaxurl:
        "https:\/\/wp.webtend.net\/noxfolio\/wp-admin\/admin-ajax.php",
    },
    nonces: { floatingButtonsClickTracking: "963e4e4ad1" },
    swiperClass: "swiper",
    settings: { page: [], editorPreferences: [] },
    kit: {
      active_breakpoints: [
        "viewport_mobile",
        "viewport_tablet",
        "viewport_tablet_extra",
        "viewport_laptop",
      ],
      lightbox_enable_counter: "yes",
      lightbox_enable_fullscreen: "yes",
      lightbox_enable_zoom: "yes",
      lightbox_enable_share: "yes",
      lightbox_title_src: "title",
      lightbox_description_src: "description",
    },
    post: {
      id: 394,
      title: "Home%20Two%20%E2%80%93%20Noxfolio",
      excerpt: "",
      featuredImage: !1,
    },
  };